apiVersion: v1
kind: Pod
metadata:
  name: webserver
  labels:
    app: web
spec:
  containers:
    - name: web-servers
      image: imcsk8/centos-nginx
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 80

