apiVersion: v1
kind: ReplicationController
metadata:
  name: webserver
spec:
  replicas: 3
  selector:
    app: web
  template:
    metadata:
      name: nginx-replicator
      labels:
        app: web
    spec:
      containers:
      - name: web-servers
        image: imcsk8/centos-nginx
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80

